'use client'

import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { useAuth } from '@/lib/auth'
import Navbar from '@/components/Navbar'
import { apiGetQuote, apiBindPolicy } from '@/lib/api'
import { formatINR } from '@/lib/utils'
import { ArrowLeft, ShieldCheck, AlertOctagon, TrendingDown, TrendingUp, Cpu, Info } from 'lucide-react'

export default function QuoteDetail() {
    const { user } = useAuth()
    const { id } = useParams()
    const router = useRouter()
    const [quote, setQuote] = useState<any>(null)
    const [loading, setLoading] = useState(true)
    const [binding, setBinding] = useState(false)
    const [error, setError] = useState('')

    useEffect(() => {
        if (!id) return
        apiGetQuote(id as string)
            .then(setQuote)
            .catch(e => setError(e.message))
            .finally(() => setLoading(false))
    }, [id])

    const handlePurchase = async () => {
        if (!quote.eligible) return
        setError('')
        setBinding(true)
        try {
            const pol = await apiBindPolicy(quote.id)
            router.push(`/policies/${pol.id}`)
        } catch (err: any) {
            setError(err.message)
            setBinding(false)
        }
    }

    if (loading) return null

    if (error) {
        return (
            <>
                <Navbar />
                <div className="container mx-auto px-4 py-8 text-center text-red-500">{error}</div>
            </>
        )
    }

    return (
        <>
            <Navbar />
            <div className="container mx-auto px-4 py-8 max-w-4xl">
                <div className="mb-6">
                    <button onClick={() => router.back()} className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1 transition-colors">
                        <ArrowLeft className="h-4 w-4" /> Back
                    </button>
                </div>

                <div className="flex flex-col md:flex-row gap-6">
                    <div className="flex-1 space-y-6">
                        <div>
                            <h1 className="text-3xl font-bold tracking-tight">Coverage Quote</h1>
                            <p className="text-muted-foreground mt-1">
                                Risk pricing generated by PMRI Global Engine • v{quote.ml_inference?.model_version || '1.0'}
                            </p>
                        </div>

                        <div className="card p-6 border-l-4 border-l-primary">
                            <h2 className="text-sm font-semibold text-muted-foreground mb-4 uppercase tracking-wider">Requested Coverage</h2>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <p className="text-xs text-muted-foreground">Term Length</p>
                                    <p className="font-medium text-lg capitalize">{quote.term.toLowerCase()}</p>
                                </div>
                                <div>
                                    <p className="text-xs text-muted-foreground">Underlying Value</p>
                                    <p className="font-medium text-lg">{formatINR(quote.portfolio_value_inr)}</p>
                                </div>
                                <div className="col-span-2">
                                    <p className="text-xs text-muted-foreground">Insured Notional Limit</p>
                                    <p className="font-bold text-2xl text-primary">{formatINR(quote.notional_inr)}</p>
                                </div>
                            </div>
                        </div>

                        <div className="card p-6">
                            <h2 className="text-sm font-semibold text-muted-foreground mb-4 uppercase tracking-wider flex items-center gap-2">
                                <Cpu className="h-4 w-4" /> ML Risk Analysis
                            </h2>
                            <div className="grid grid-cols-2 gap-6 pb-6 border-b border-border">
                                <div>
                                    <p className="text-xs text-muted-foreground mb-1">Portfolio Volatility (Annualized)</p>
                                    <p className="font-mono text-xl">{(quote.ml_inference?.predicted_vol * 100).toFixed(1)}%</p>
                                </div>
                                <div>
                                    <p className="text-xs text-muted-foreground mb-1">Tail-Risk Probability</p>
                                    <p className="font-mono text-xl tracking-tight text-red-400">{(quote.ml_inference?.tail_loss_prob * 100).toFixed(2)}%</p>
                                </div>
                            </div>

                            <div className="pt-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <div className="flex items-center gap-2 mb-2">
                                        <TrendingDown className="h-5 w-5 text-red-500" />
                                        <h3 className="font-semibold text-red-500">Downside Threshold</h3>
                                    </div>
                                    <p className="text-sm text-foreground/80 mb-2">Payout triggers if portfolio drops more than:</p>
                                    <p className="text-2xl font-bold font-mono">{(quote.loss_threshold * 100).toFixed(1)}%</p>
                                    <p className="text-xs text-muted-foreground mt-1">Coverage Ratio: {(quote.coverage_rate * 100).toFixed(0)}%</p>
                                </div>

                                <div>
                                    <div className="flex items-center gap-2 mb-2">
                                        <TrendingUp className="h-5 w-5 text-green-500" />
                                        <h3 className="font-semibold text-green-500">Upside Share</h3>
                                    </div>
                                    <p className="text-sm text-foreground/80 mb-2">Premium rebate if portfolio gains more than:</p>
                                    <p className="text-2xl font-bold font-mono">+{(quote.profit_threshold * 100).toFixed(1)}%</p>
                                    <p className="text-xs text-muted-foreground mt-1">Rebate Ratio: {(quote.profit_share_rate * 100).toFixed(0)}%</p>
                                </div>
                            </div>
                        </div>

                        <div className="p-4 bg-secondary/30 rounded-xl border border-border flex items-start gap-3 text-sm text-muted-foreground">
                            <Info className="h-5 w-5 shrink-0 text-primary mt-0.5" />
                            <p>
                                This quote evaluates your exact portfolio composition spanning both NSE and NASDAQ markets. Risk margins are automatically adjusted based on your account tier ({user?.tier.replace('_', ' ')}).
                            </p>
                        </div>
                    </div>

                    <div className="w-full md:w-80">
                        <div className={`card p-6 sticky top-24 ${quote.eligible ? 'border-primary/50 shadow-[0_0_20px_rgba(59,130,246,0.1)]' : 'border-red-500/50'}`}>
                            <h2 className="text-xl font-bold border-b border-border pb-4 mb-4">Pricing Summary</h2>

                            <div className="space-y-3 mb-6">
                                <div className="flex justify-between text-sm">
                                    <span className="text-muted-foreground">Expected Loss</span>
                                    <span className="font-medium font-mono">{formatINR(quote.expected_payout)}</span>
                                </div>
                                <div className="flex justify-between text-sm">
                                    <span className="text-muted-foreground">Risk Margin</span>
                                    <span className="font-medium font-mono">{formatINR(quote.risk_margin)}</span>
                                </div>
                                <div className="flex justify-between text-sm">
                                    <span className="text-muted-foreground">Capital Charge</span>
                                    <span className="font-medium font-mono">{formatINR(quote.capital_fee)}</span>
                                </div>
                            </div>

                            <div className="border-t border-border pt-4 mb-8">
                                <div className="flex justify-between items-center mb-1">
                                    <span className="font-semibold text-lg">Total Premium</span>
                                    <span className="font-bold text-2xl text-primary font-mono">{formatINR(quote.premium_inr)}</span>
                                </div>
                                {quote.premium_inr < 500 && (
                                    <p className="text-[10px] text-muted-foreground text-right">*Minimum premium applied</p>
                                )}
                            </div>

                            {quote.eligible ? (
                                <button
                                    onClick={handlePurchase}
                                    disabled={binding}
                                    className="btn-primary w-full py-4 text-lg shadow-lg flex justify-center items-center gap-2"
                                >
                                    {binding ? 'Binding...' : <><ShieldCheck className="h-5 w-5" /> Bind Policy</>}
                                </button>
                            ) : (
                                <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
                                    <div className="flex items-center gap-2 text-red-500 font-semibold mb-2">
                                        <AlertOctagon className="h-5 w-5" /> Underwriting Rejected
                                    </div>
                                    <ul className="text-xs text-red-400 space-y-1 pl-5 list-disc">
                                        {quote.eligibility_reasons.map((r: string, i: number) => <li key={i}>{r}</li>)}
                                    </ul>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
